### ISSUE TITLE
ブログ仕様書作成

### ISSUE THREAD

**Issue by f91seed** [zunda-cafe/zunda-devstudy#1]
### 作業内容
* スタートアップとなる仕様書をSphinxを用いて作成すること 

### 完了定義
* Sphinxを用いた仕様書が作成されていること
* アクセス方法などの情報が本Issueにまとめられていること

**Comment by naninuneter55** [comment]
仕様書を sunday-devstudy-doc リポジトリのGitHub Pagesに公開しました。

* https://zunda-cafe.github.io/zunda-devstudy-doc/

Sphinxのソースファイル及び解説は sunday-devstudy-doc リポジトリを参照してください。
