### ISSUE TITLE
Travis-CI連携

### ISSUE THREAD

**Issue by f91seed** [zunda-cafe/zunda-devstudy#2]
### 作業内容
* Travis-CIとGitHubを連携させ、CI/CD環境を構築する

### 完了定義
* 連携するための方法や手順が本Issueにまとめられていること

**Comment by yk0nno** [comment]
まずは連携を設定しました。
https://travis-ci.org/zunda-cafe/zunda-devstudy

他の人から設定も可能なようになってるんでしょうか？ アクセス権の設定が見当たらず、わかってません。

**Comment by f91seed** [comment]
上記の連携設定コメントのサイトにアクセスしたら見れました。
なので、共有化は正常にできていると思います

**Comment by yk0nno** [comment]
@f91seed Travisってサイト自体はパブリックで、ビルド状況なんかはログインしなくても見れると思います。
[このsettingページ](https://travis-ci.org/zunda-cafe/zunda-devstudy/settings)はどうでしょう。

---
デフォルトはメール通知のようなので、そっちは止めてslack通知とする。
アクセストークンは暗号化して、`.travis.yml`に埋め込む。
TravisCI-Slackの連携設定 ･･･ http://qiita.com/nwtgck/items/17840855cb76f60fa1fe
上記で必要なtravisコマンドの使用準備 ・・・ https://github.com/travis-ci/travis.rb#installation

**Comment by yk0nno** [comment]
* mvnw がPermissionDeniedで怒られる場合
  * こうなる -> https://travis-ci.org/maruhachi/line-bot-kun/builds/278918576
  * 対処例： [Travis.yml ./gradlew : Permission denied - StackOverFlow](https://stackoverflow.com/questions/33820638/travis-yml-gradlew-permission-denied)

* [SpringBootプロジェクトの設定例](https://github.com/spring-projects/spring-boot/blob/master/.travis.yml)

私の環境はこれでOKでした。
